from . import res_users
from . import asset_department
from . import asset_category
from . import asset_activity_log
from . import asset_asset
from . import asset_allocation
from . import asset_transfer
from . import resource_booking
from . import asset_maintenance_request
